### ISSUE TITLE
MacOS Build Issue

### ISSUE THREAD

**Issue by joshuarubin** [alexaandru/go-tree-sitter-bare#2]
When trying to build on MacOS I'm getting:

```
# github.com/alexaandru/go-tree-sitter-bare
/Users/jrubin/go/pkg/mod/github.com/alexaandru/go-tree-sitter-bare@v1.7.2/query.go:424:72: cannot use _Ctype_ulong(micros) (value of type _Ctype_ulong) as _Ctype_uint64_t value in variable declaration
```

I don't see this on linux

**Comment by joshuarubin** [comment]
https://github.com/alexaandru/go-tree-sitter-bare/blob/a1bb2eb27ccacfda11ba15d5e0878df92c52248d/query.go#L424

should be changed to:
```go
C.ts_query_cursor_set_timeout_micros(c.c, C.uint64_t(micros))
```

**Comment by alexaandru** [comment]
Much appreciated! :-) I didn't see any other uses of `C.ulong` so hopefully, it works after this change?
